# Release Drafter configuration
# https://github.com/release-drafter/release-drafter

name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

template: |
  ## What’s changed

  $CHANGES

categories:
  - title: '🚀 Features'
    labels:
      - feature
      - enhancement
  - title: '🐛 Bug Fixes'
    labels:
      - fix
      - bug
  - title: '🧰 Maintenance'
    labels:
      - chore

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
